name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint & TS Check
        run: pnpm check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - vite-version: '2.9'
            plugin-react-version: '1'
          - vite-version: '3'
            plugin-react-version: '3'
          - vite-version: '4'
            plugin-react-version: '4'
          - vite-version: '5'
            plugin-react-version: '4'
          - vite-version: '6'
            plugin-react-version: '4'
          - vite-version: '7'
            plugin-react-version: '4'

    name: test (vite@${{ matrix.vite-version }})

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/Cypress
          key:
            ${{ runner.os }}-pnpm-store-vite${{ matrix.vite-version }}-${{
            hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-vite${{ matrix.vite-version }}-
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i

      - name: Override Vite version
        run:
          pnpm --filter example add vite@${{ matrix.vite-version }}
          @vitejs/plugin-react@${{ matrix.plugin-react-version }}

      - name: Run Tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          build: pnpm build
          start: pnpm example dev
          command: pnpm example test:ci
