name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint & TS Check
        run: pnpm check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - &matrix-defaults
            vite-version: 8
            plugin-react-version: 6
            cypress-version: 14
            chokidar-version: 5
            debug-version: 4

          # Each permitted Vite version against same version of Cypress
          - <<: *matrix-defaults
            vite-version: '2.9'
            plugin-react-version: 1
          - <<: *matrix-defaults
            vite-version: 3
            plugin-react-version: 2
          - <<: *matrix-defaults
            vite-version: 4
            plugin-react-version: 3
          - <<: *matrix-defaults
            vite-version: 5
            plugin-react-version: 4
          - <<: *matrix-defaults
            vite-version: 6
            plugin-react-version: 4
          - <<: *matrix-defaults
            vite-version: 7
            plugin-react-version: 4
          # listed below
          # - <<: *matrix-defaults
          #   vite-version: 8
          #   plugin-react-version: 6

          # Each Cypress version against latest permitted Vite version,
          # testing permitted versions of other peerDependencies at the same time.
          - <<: *matrix-defaults
            cypress-version: 12
            chokidar-version: 2
            debug-version: 2
          - <<: *matrix-defaults
            cypress-version: 13
            chokidar-version: 3
            debug-version: 2
          - <<: *matrix-defaults
            cypress-version: 14
            chokidar-version: 4
            debug-version: 3
          - <<: *matrix-defaults
            cypress-version: 15
            chokidar-version: 5
            debug-version: 4

    name:
      test (vite@${{ matrix.vite-version }}, cypress@${{ matrix.cypress-version
      }}, chokidar@${{ matrix.chokidar-version }}, debug@${{
      matrix.debug-version }})

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v5
        name: Setup pnpm cache
        env:
          CACHE_KEY_PREFIX:
            ${{ runner.os }}-pnpm-store-vite${{ matrix.vite-version
            }}-cypress${{ matrix.cypress-version }}-chokidar${{
            matrix.chokidar-version }}-debug${{ matrix.debug-version }}
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
            ~/.cache/Cypress
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-

      - name: Install dependencies
        run: pnpm i

      - name: Override dependency versions
        run:
          pnpm --filter example add vite@${{ matrix.vite-version }}
          @vitejs/plugin-react@${{ matrix.plugin-react-version }} cypress@${{
          matrix.cypress-version }} chokidar@${{ matrix.chokidar-version }}
          debug@${{ matrix.debug-version }}

      - name: Run Tests
        uses: cypress-io/github-action@v7.1.10
        with:
          install: false
          build: pnpm build
          start: pnpm example dev
          command: pnpm example test:ci
