name: Close stale issues
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: 'stale'
          stale-issue-message:
            This issue is automatically marked as stale because it has been open
            for 30 days with no activity. Remove the stale label or leave a
            comment, or it will be closed in 14 days.
          close-issue-message:
            'This issue was closed because it has been stalled for 14 days with
            no activity. Please feel free to open a new issue if you have any
            further questions.'
          days-before-pr-stale: -1
          days-before-pr-close: -1
